name: Test release nieuwe versie

on:
    workflow_dispatch:
        inputs:
            merge-develop-to-main:
                type: boolean
                description: Merge develop to main
                default: false

jobs:
    release:
        uses: bakerware/release-strategy-action/.github/workflows/test-release-project.yml@main
        secrets: inherit
        with:
            project: CN
            merge-to-develop: ${{ inputs.merge-develop-to-main }}
