name: Test Release

on:
    workflow_call:
        inputs:
            project:
                type: string
                required: true
            merge-to-develop:
                type: boolean
                required: true
                default: false

jobs:
    merge:
        if: ${{ inputs.merge-to-develop }} === true
        runs-on: ubuntu-latest
        steps:
            -   name: Merge develop into main
                uses: tukasz/direct-merge-action@master
                with:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    owner: BakerWare
                    repo: ${{ github.event.repository.name }}
                    source-branch: develop
                    target-branch: main

    release:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Do something
                uses: BakerWare/release-strategy-action@main
                env:
                    JIRA_USER: ${{ secrets.JIRA_USER }}
                    JIRA_PASS: ${{ secrets.JIRA_PASS }}
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    PROJECT: ${{ inputs.project }}


