name: Test Release

on:
    workflow_call:
        inputs:
            project:
                type: string
                required: true
            merge-to-develop:
                type: boolean
                required: true
                default: false

jobs:
    merge:
        if: ${{ inputs.merge-to-develop }}
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Merge develop -> main
                uses: devmasx/merge-branch@master
                with:
                    type: now
                    from_branch: develop
                    target_branch: main
                    github_token: ${{ github.token }}
                    message: Merge develop into main

    release:
        needs: merge
        runs-on: ubuntu-latest
        # if: always() # Workaround because this job has to run after merge and needs that job if activated
        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Do something
                uses: BakerWare/release-strategy-action@main
                env:
                    JIRA_USER: ${{ secrets.JIRA_USER }}
                    JIRA_PASS: ${{ secrets.JIRA_PASS }}
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    PROJECT: ${{ inputs.project }}



